# [START gae_quickstart_yaml]
runtime: nodejs8
# [END gae_quickstart_yaml]

handlers:
- url: /api/.*
  script: auto
- url: /
  static_files: angular-app/dist/angular-app/index.html
  upload: angular-app/dist/angular-app/index.html
- url: /
  static_dir: angular-app/dist/angular-app